import gochizo_default from "@/assets/img/gochizo/gochizo_default.png";

const gochizoArchive = {
    A017: {
        name: "跳跃软糖（多汁）",
        RrA: "97",
        RrB: "97",
        image: gochizo_default,
    },
    A018: {
        name: "飞踢软糖",
        RrA: "97",
        RrB: "135",
        image: gochizo_default,
    },
    A019: {
        name: "拳击软糖",
        RrA: "97",
        RrB: "156",
        image: gochizo_default,
    },
    A020: {
        name: "钓鱼软糖",
        RrA: "97",
        RrB: "181",
        image: gochizo_default,
    },
    A021: {
        name: "惊异软糖",
        RrA: "97",
        RrB: "196",
        image: gochizo_default,
    },
    A022: {
        name: "火花软糖",
        RrA: "97",
        RrB: "206",
        image: gochizo_default,
    },
    A023: {
        name: "脆脆薯片（脆脆）",
        RrA: "97",
        RrB: "215",
        image: gochizo_default,
    },
    A026: {
        name: "火辣薯片",
        RrA: "97",
        RrB: "236",
        image: gochizo_default,
    },
    A027: {
        name: "巧克弹（啪唧啪唧）",
        RrA: "97",
        RrB: "239",
        image: gochizo_default,
    },
    A028: {
        name: "巧克咚",
        RrA: "97",
        RrB: "242",
        image: gochizo_default,
    },
    A030: {
        name: "巧克比",
        RrA: "135",
        RrB: "135",
        image: gochizo_default,
    },
    A031: {
        name: "挖宝巧克力（啪唧啪唧）",
        RrA: "135",
        RrB: "156",
        image: gochizo_default,
    },
    A032: {
        name: "巧库力（啪唧啪唧）",
        RrA: "135",
        RrB: "181",
        image: gochizo_default,
    },
    A033: {
        name: "巧库力",
        RrA: "135",
        RrB: "196",
        image: gochizo_default,
    },
    A034: {
        name: "软棉花糖（软绵绵）",
        RrA: "135",
        RrB: "206",
        image: gochizo_default,
    },
    A035: {
        name: "圆花糖",
        RrA: "135",
        RrB: "215",
        image: gochizo_default,
    },
    A036: {
        name: "涡轮糖果",
        RrA: "135",
        RrB: "226",
        image: gochizo_default,
    },
    A037: {
        name: "转圈糖果（舔一舔）",
        RrA: "135",
        RrB: "231",
        image: gochizo_default,
    },
    A038: {
        name: "爆糖果",
        RrA: "135",
        RrB: "236",
        image: gochizo_default,
    },
    A039: {
        name: "气泡汽水糖",
        RrA: "135",
        RrB: "239",
        image: gochizo_default,
    },
    A040: {
        name: "气泡汽水糖（咯嚓咯嚓）",
        RrA: "135",
        RrB: "242",
        image: gochizo_default,
    },
    A044: {
        name: "毛绒跳跳糖（毛茸茸）",
        RrA: "156",
        RrB: "181",
        image: gochizo_default,
    },
    A047: {
        name: "爆响米花（砰砰）",
        RrA: "156",
        RrB: "215",
        image: gochizo_default,
    },
    A049: {
        name: "圆饼（咯嚓咯嚓）",
        RrA: "156",
        RrB: "231",
        image: gochizo_default,
    },
    A050: {
        name: "摇晃果冻（摇摇晃晃）",
        RrA: "156",
        RrB: "236",
        image: gochizo_default,
    },
    A051: {
        name: "优雅马卡龙（高贵）",
        RrA: "156",
        RrB: "239",
        image: gochizo_default,
    },
    A052: {
        name: "甜甜圈（毛茸茸）",
        RrA: "156",
        RrB: "242",
        image: gochizo_default,
    },
    A053: {
        name: "焦焦奶糖（咀嚼咀嚼）",
        RrA: "181",
        RrB: "97",
        image: gochizo_default,
    },
    A054: {
        name: "曲奇奇（咯嚓咯嚓）",
        RrA: "181",
        RrB: "135",
        image: gochizo_default,
    },
    A056: {
        name: "大布丁（摇摇晃晃）",
        RrA: "181",
        RrB: "181",
        image: gochizo_default,
    },
    A059: {
        name: "毛绒跳跳糖",
        RrA: "181",
        RrB: "215",
        image: gochizo_default,
    },
    A062: {
        name: "爆响米花",
        RrA: "181",
        RrB: "236",
        image: gochizo_default,
    },
    A064: {
        name: "圆饼",
        RrA: "181",
        RrB: "242",
        image: gochizo_default,
    },
    A065: {
        name: "摇晃果冻",
        RrA: "196",
        RrB: "97",
        image: gochizo_default,
    },
    A066: {
        name: "优雅马卡龙",
        RrA: "196",
        RrB: "135",
        image: gochizo_default,
    },
    A067: {
        name: "甜甜圈",
        RrA: "196",
        RrB: "156",
        image: gochizo_default,
    },
    A068: {
        name: "焦焦奶糖",
        RrA: "196",
        RrB: "181",
        image: gochizo_default,
    },
    A069: {
        name: "曲奇奇",
        RrA: "196",
        RrB: "196",
        image: gochizo_default,
    },
    A071: {
        name: "大布丁",
        RrA: "196",
        RrB: "215",
        image: gochizo_default,
    },
    A073: {
        name: "射击零食（脆脆）",
        RrA: "196",
        RrB: "231",
        image: gochizo_default,
    },
    A074: {
        name: "尖刺零食（脆脆）",
        RrA: "196",
        RrB: "236",
        image: gochizo_default,
    },
    A075: {
        name: "下午茶点心（啪唧啪唧）",
        RrA: "196",
        RrB: "239",
        image: gochizo_default,
    },
    A076: {
        name: "点心（啪唧啪唧）",
        RrA: "196",
        RrB: "232",
        image: gochizo_default,
    },
    A077: {
        name: "巧克弹",
        RrA: "206",
        RrB: "97",
        image: gochizo_default,
    },
    A078: {
        name: "射击零食",
        RrA: "206",
        RrB: "135",
        image: gochizo_default,
    },
    A079: {
        name: "尖刺零食",
        RrA: "206",
        RrB: "156",
        image: gochizo_default,
    },
    A080: {
        name: "挖宝巧克力",
        RrA: "206",
        RrB: "181",
        image: gochizo_default,
    },
    A081: {
        name: "点心",
        RrA: "206",
        RrB: "196",
        image: gochizo_default,
    },
    A082: {
        name: "巧克弹",
        RrA: "206",
        RrB: "206",
        image: gochizo_default,
    },
    A083: {
        name: "土豆扫尾（脆脆）",
        RrA: "206",
        RrB: "215",
        image: gochizo_default,
    },
    A084: {
        name: "盾牌零食（脆脆）",
        RrA: "206",
        RrB: "226",
        image: gochizo_default,
    },
    A085: {
        name: "土豆扫尾",
        RrA: "206",
        RrB: "231",
        image: gochizo_default,
    },
    A086: {
        name: "盾牌扫尾",
        RrA: "206",
        RrB: "236",
        image: gochizo_default,
    },
    A089: {
        name: "特殊",
        RrA: "215",
        RrB: "97",
        image: gochizo_default,
    },
    A090: {
        name: "庆祝",
        RrA: "215",
        RrB: "135",
        image: gochizo_default,
    },
    A091: {
        name: "圣诞",
        RrA: "215",
        RrB: "156",
        image: gochizo_default,
    },
    A092: {
        name: "新年快乐",
        RrA: "215",
        RrB: "181",
        image: gochizo_default,
    },
    A093: {
        name: "音乐",
        RrA: "215",
        RrB: "196",
        image: gochizo_default,
    },
    A094: {
        name: "庆祝",
        RrA: "215",
        RrB: "206",
        image: gochizo_default,
    },
    A095: {
        name: "假面骑士空我",
        RrA: "215",
        RrB: "215",
        image: gochizo_default,
    },
    A096: {
        name: "假面骑士亚吉陀",
        RrA: "215",
        RrB: "226",
        image: gochizo_default,
    },
    A097: {
        name: "假面骑士龙骑",
        RrA: "215",
        RrB: "231",
        image: gochizo_default,
    },
    A098: {
        name: "假面骑士Faiz",
        RrA: "215",
        RrB: "236",
        image: gochizo_default,
    },
    A099: {
        name: "假面骑士Blade",
        RrA: "215",
        RrB: "239",
        image: gochizo_default,
    },
    A100: {
        name: "假面骑士响鬼",
        RrA: "215",
        RrB: "242",
        image: gochizo_default,
    },
    A101: {
        name: "假面骑士Kabuto",
        RrA: "226",
        RrB: "97",
        image: gochizo_default,
    },
    A102: {
        name: "假面骑士Den-O",
        RrA: "226",
        RrB: "135",
        image: gochizo_default,
    },
    A103: {
        name: "假面骑士Kiva",
        RrA: "226",
        RrB: "156",
        image: gochizo_default,
    },
    A104: {
        name: "假面骑士Decade",
        RrA: "226",
        RrB: "181",
        image: gochizo_default,
    },
    A105: {
        name: "假面骑士W",
        RrA: "226",
        RrB: "196",
        image: gochizo_default,
    },
    A106: {
        name: "假面骑士OOO",
        RrA: "226",
        RrB: "206",
        image: gochizo_default,
    },
    A107: {
        name: "假面骑士Fource",
        RrA: "226",
        RrB: "215",
        image: gochizo_default,
    },
    A108: {
        name: "假面骑士Wizard",
        RrA: "226",
        RrB: "226",
        image: gochizo_default,
    },
    A109: {
        name: "假面骑士铠武",
        RrA: "226",
        RrB: "231",
        image: gochizo_default,
    },
    A110: {
        name: "假面骑士Drive",
        RrA: "226",
        RrB: "236",
        image: gochizo_default,
    },
    A111: {
        name: "假面骑士Ghost",
        RrA: "226",
        RrB: "239",
        image: gochizo_default,
    },
    A112: {
        name: "假面骑士EX-Aid",
        RrA: "226",
        RrB: "243",
        image: gochizo_default,
    },
    A113: {
        name: "假面骑士Build",
        RrA: "231",
        RrB: "97",
        image: gochizo_default,
    },
    A114: {
        name: "假面骑士Zio",
        RrA: "231",
        RrB: "135",
        image: gochizo_default,
    },
    A115: {
        name: "假面骑士01",
        RrA: "231",
        RrB: "156",
        image: gochizo_default,
    },
    A116: {
        name: "假面骑士Saber",
        RrA: "231",
        RrB: "181",
        image: gochizo_default,
    },
    A117: {
        name: "假面骑士Revi",
        RrA: "231",
        RrB: "196",
        image: gochizo_default,
    },
    A118: {
        name: "假面骑士Vice",
        RrA: "231",
        RrB: "206",
        image: gochizo_default,
    },
    A119: {
        name: "假面骑士极狐",
        RrA: "231",
        RrB: "215",
        image: gochizo_default,
    },
    A120: {
        name: "假面骑士太狸",
        RrA: "231",
        RrB: "226",
        image: gochizo_default,
    },
    A121: {
        name: "假面骑士霸牛",
        RrA: "231",
        RrB: "231",
        image: gochizo_default,
    },
    A122: {
        name: "假面骑士娜猫",
        RrA: "231",
        RrB: "236",
        image: gochizo_default,
    },
    A123: {
        name: "假面骑士歌查德",
        RrA: "231",
        RrB: "239",
        image: gochizo_default,
    },
    A124: {
        name: "假面骑士雷杰德",
        RrA: "231",
        RrB: "242",
        image: gochizo_default,
    },
    A125: {
        name: "假面骑士玛杰德",
        RrA: "236",
        RrB: "97",
        image: gochizo_default,
    },
    A126: {
        name: "假面骑士吉恩",
        RrA: "236",
        RrB: "135",
        image: gochizo_default,
    },
    A127: {
        name: "假面骑士瓦尔巴拉德",
        RrA: "236",
        RrB: "156",
        image: gochizo_default,
    },
    A128: {
        name: "假面骑士1号",
        RrA: "236",
        RrB: "181",
        image: gochizo_default,
    },
    A129: {
        name: "假面骑士巴尔坎",
        RrA: "236",
        RrB: "196",
        image: gochizo_default,
    },
    A130: {
        name: "假面骑士剑锋",
        RrA: "236",
        RrB: "206",
        image: gochizo_default,
    },
    A131: {
        name: "假面骑士莱伊布",
        RrA: "236",
        RrB: "215",
        image: gochizo_default,
    },
    A132: {
        name: "超级战队",
        RrA: "236",
        RrB: "226",
        image: gochizo_default,
    },
    A133: {
        name: "超级英雄",
        RrA: "236",
        RrB: "231",
        image: gochizo_default,
    },
    A134: {
        name: "奔奔者",
        RrA: "236",
        RrB: "236",
        image: gochizo_default,
    },
    A135: {
        name: "下午茶点心（咀嚼咀嚼）",
        RrA: "236",
        RrB: "239",
        image: gochizo_default,
    },
    A136: {
        name: "点心（咀嚼咀嚼）",
        RrA: "236",
        RrB: "242",
        image: gochizo_default,
    },
    A137: {
        name: "下午茶点心",
        RrA: "239",
        RrB: "97",
        image: gochizo_default,
    },
    A138: {
        name: "点心",
        RrA: "239",
        RrB: "135",
        image: gochizo_default,
    },
    A139: {
        name: "点心（咯嚓咯嚓）",
        RrA: "239",
        RrB: "156",
        image: gochizo_default,
    },
    A140: {
        name: "下午茶点心（咯嚓咯嚓）",
        RrA: "239",
        RrB: "181",
        image: gochizo_default,
    },
    A141: {
        name: "点心",
        RrA: "239",
        RrB: "196",
        image: gochizo_default,
    },
    A142: {
        name: "下午茶点心",
        RrA: "239",
        RrB: "206",
        image: gochizo_default,
    },
    A143: {
        name: "下午茶点心（多汁）",
        RrA: "239",
        RrB: "215",
        image: gochizo_default,
    },
    A144: {
        name: "点心（多汁）",
        RrA: "239",
        RrB: "226",
        image: gochizo_default,
    },
    A145: {
        name: "下午茶点心",
        RrA: "239",
        RrB: "231",
        image: gochizo_default,
    },
    A146: {
        name: "点心",
        RrA: "239",
        RrB: "236",
        image: gochizo_default,
    },
    A147: {
        name: "点心（舔一舔）",
        RrA: "239",
        RrB: "239",
        image: gochizo_default,
    },
    A148: {
        name: "下午茶点心（舔一舔）",
        RrA: "239",
        RrB: "242",
        image: gochizo_default,
    },
    A149: {
        name: "点心",
        RrA: "242",
        RrB: "97",
        image: gochizo_default,
    },
    A150: {
        name: "下午茶点心",
        RrA: "242",
        RrB: "135",
        image: gochizo_default,
    },
    A151: {
        name: "蛋糕王（惊异）",
        RrA: "242",
        RrB: "156",
        image: gochizo_default,
    },
    A152: {
        name: "圣诞树桩蛋糕（软绵绵）",
        RrA: "242",
        RrB: "181",
        image: gochizo_default,
    },
    A153: {
        name: "假面骑士加布",
        RrA: "242",
        RrB: "196",
        image: gochizo_default,
    },
    A154: {
        name: "假面骑士新骑士",
        RrA: "242",
        RrB: "206",
        image: gochizo_default,
    },
    A155: {
        name: "假面骑士新英雄",
        RrA: "242",
        RrB: "215",
        image: gochizo_default,
    },
    A156: {
        name: "假面骑士",
        RrA: "242",
        RrB: "226",
        image: gochizo_default,
    },
};

export default {
    gochizoArchive,
};